name: Run Tests

on: [push, pull_request]

jobs:
  build:

    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v2

    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.x

    - name: Install Nuget Packages
      run: dotnet nuget install "SpaceEngineers.ScriptingReferences"
           dotnet nuget install "Malware.MDK-SE"
    - name: Build
      run: dotnet build ./EasyCommands/EasyCommands.csproj --configuration Release
