name: Run Tests

on: [push, pull_request]

jobs:
  build:
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v2

    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.x

    - name: Install SpaceEngineers Nuget Packages
      run: nuget install "SpaceEngineers.ScriptingReferences" -OutputDirectory "packages"
      
    - name: Install MDK Nuget Packages
      run: nuget install "Malware.MDK-SE" -OutputDirectory "packages"

    - name: Print File Structure
      run: dir

    - name: Build
      run: dotnet build ./EasyCommands/EasyCommands.csproj --configuration Release
